In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [3]:
print(a)
print(b)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
#get dimension
a.ndim
b.ndim

2

In [6]:
#get shape
a.shape
b.shape

(2, 3)

In [8]:
#get data type
a.dtype
b.dtype

dtype('float64')

In [9]:
x=np.array([1,2,3],dtype='int16')
x.dtype

dtype('int16')

In [10]:
x.itemsize

2

In [11]:
x.size*x.itemsize

6

In [12]:
x.nbytes

6

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
#get specific element
a[1,5]

13

In [15]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#get specific column
a[:,2]

array([ 3, 10])

In [17]:
#[startIndex:endIndex:stepSize]
a[0 ,1:6:2]

array([2, 4, 6])

In [18]:
#changing element
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
a[:,5]=5
print(a)

[[ 1  2  3  4  5  5  7]
 [ 8  9 10 11 12  5 14]]


In [20]:
a[0,:]=90
print(a)

[[90 90 90 90 90 90 90]
 [ 8  9 10 11 12  5 14]]


In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [26]:
#random decimal numbers
np.random.rand(4,2)

array([[0.15458055, 0.77309483],
       [0.0934619 , 0.57022772],
       [0.51394729, 0.22946288],
       [0.10449302, 0.88462686]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#repeating an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [36]:
#print matrix
a=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [35]:
target=np.ones((5,5));
print(target)
insideTarget=np.zeros((3,3));
insideTarget[1,1]=9;
print(insideTarget)
# target[1:4,1:4]=insideTarget;
target[1:-1,1:-1]=insideTarget;
print(target)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
#be careful when copying arrays
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


In [38]:
#instead
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [39]:
#mathematic
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [40]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
#linear algebra
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
#find determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [45]:
#statistics with numpy
stats=np.array([[1,2,3],[4,5,6]])
stats
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))
print(np.mean(stats))
print(np.median(stats))
print(np.std(stats))
print(np.var(stats))
print(np.corrcoef(stats))
print(np.cov(stats))

1
6
21
3.5
3.5
1.707825127659933
2.9166666666666665
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [46]:
print(np.min(stats,axis=1));
print(np.max(stats,axis=0));

[1 4]
[4 5 6]


In [47]:
#reorganizing array
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [48]:
#vertical stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
#horizontal stacking vectors
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
#miscellaneous and advanced indexing done by importing file
# filedata=np.genfromtxt('data.txt',delimiter=',')
# filedata=filedata.astype('int32')
# print(filedata)
# #advanced indexing
# filedata>50
# filedata[filedata>50]