In [12]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Load the Wine dataset
wine = datasets.load_wine()
X = wine.data
y = wine.target

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train and evaluate with linear kernel
svm_linear = SVC(kernel='linear', C=1.0, random_state=42)
svm_linear.fit(X_train, y_train)
y_pred_linear = svm_linear.predict(X_test)
accuracy_linear = svm_linear.score(X_test, y_test) * 100
print("Linear Kernel SVM Accuracy: {:.2f}%".format(accuracy_linear))
print(classification_report(y_test, y_pred_linear))
print(confusion_matrix(y_test, y_pred_linear))

# Train and evaluate with RBF kernel
svm_rbf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)
accuracy_rbf = svm_rbf.score(X_test, y_test) * 100
print("RBF Kernel SVM Accuracy: {:.2f}%".format(accuracy_rbf))
print(classification_report(y_test, y_pred_rbf))
print(confusion_matrix(y_test, y_pred_rbf))

# Train and evaluate with polynomial kernel
svm_poly = SVC(kernel='poly', degree=3, C=1.0, gamma='scale', random_state=42)
svm_poly.fit(X_train, y_train)
y_pred_poly = svm_poly.predict(X_test)
accuracy_poly = svm_poly.score(X_test, y_test) * 100
print("Polynomial Kernel SVM Accuracy: {:.2f}%".format(accuracy_poly))
print(classification_report(y_test, y_pred_poly))
print(confusion_matrix(y_test, y_pred_poly))


Linear Kernel SVM Accuracy: 98.15%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.95      0.98        21
           2       0.93      1.00      0.97        14

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54

[[19  0  0]
 [ 0 20  1]
 [ 0  0 14]]
RBF Kernel SVM Accuracy: 98.15%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.95      1.00      0.98        21
           2       1.00      0.93      0.96        14

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54

[[19  0  0]
 [ 0 21  0]
 [ 0  1 13]]
Polynomial Kernel SVM Accuracy: 96.30%
              precision    recall  f1-score   support

   